include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_print
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - always_declare_return_types
    - avoid_dynamic_calls
    - avoid_void_async
